# Generated by Django 4.2.5 on 2023-09-21 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=100, verbose_name='상품 ID')),
                ('user_id', models.IntegerField(verbose_name='수신자 ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='생성일자')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('location', models.CharField(max_length=100, verbose_name='지역')),
                ('img', models.CharField(max_length=100, verbose_name='이미지')),
                ('description', models.TextField(verbose_name='설명')),
                ('user_id', models.IntegerField(verbose_name='작성자 ID')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('view_num', models.IntegerField(default=0, verbose_name='조회수')),
                ('chat_num', models.IntegerField(default=0, verbose_name='채팅수')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='생성일자')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='발신자 ID')),
                ('message', models.TextField(verbose_name='내용')),
                ('read_or_not', models.BooleanField(default=False, verbose_name='읽기 여부')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='생성일자')),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.chatroom')),
            ],
        ),
    ]
