# Generated by Django 4.2.5 on 2023-09-26 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_chat_userprofile_alter_post_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('price', models.IntegerField(verbose_name='시급')),
                ('description', models.TextField(verbose_name='설명')),
                ('location', models.CharField(max_length=100, verbose_name='지역')),
                ('images', models.ImageField(upload_to='post_images/', verbose_name='이미지')),
                ('working_days', models.CharField(max_length=100, verbose_name='근무 요일')),
                ('working_time', models.CharField(max_length=100, verbose_name='근무 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='작성일자')),
                ('product_sold', models.CharField(default='N', max_length=1, verbose_name='마감여부')),
                ('view_num', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('chat_num', models.PositiveIntegerField(default=0, verbose_name='채팅수')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
