# Generated by Django 4.2.5 on 2023-09-27 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_alter_chat_options_alter_chat_user_chatroom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('property_type', models.CharField(default='아파트', max_length=50, verbose_name='매물종류')),
                ('deposit', models.IntegerField(verbose_name='보증금')),
                ('monthly_rent', models.IntegerField(verbose_name='월세')),
                ('area', models.IntegerField(verbose_name='면적')),
                ('rooms', models.IntegerField(verbose_name='방개수')),
                ('floor', models.IntegerField(verbose_name='층')),
                ('available_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='입주가능일')),
                ('pet', models.CharField(default='N', max_length=1, verbose_name='반려동물')),
                ('parking', models.CharField(default='N', max_length=1, verbose_name='주차')),
                ('elevator', models.CharField(default='N', max_length=1, verbose_name='엘리베이터')),
                ('description', models.TextField(verbose_name='설명')),
                ('location', models.CharField(max_length=100, verbose_name='지역')),
                ('images', models.ImageField(upload_to='realty_images/', verbose_name='이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='작성일자')),
                ('product_sold', models.CharField(default='N', max_length=1, verbose_name='거래여부')),
                ('view_num', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('chat_num', models.PositiveIntegerField(default=0, verbose_name='채팅수')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Oldcar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('car_info', models.TextField(verbose_name='차량 정보')),
                ('insurance_history', models.TextField(verbose_name='보험 이력')),
                ('description', models.TextField(verbose_name='설명')),
                ('location', models.CharField(max_length=100, verbose_name='지역')),
                ('images', models.ImageField(upload_to='oldcar_images/', verbose_name='이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='작성일자')),
                ('product_sold', models.CharField(default='N', max_length=1, verbose_name='마감여부')),
                ('view_num', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('chat_num', models.PositiveIntegerField(default=0, verbose_name='채팅수')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
