# Generated by Django 4.2.5 on 2023-10-01 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_realty_oldcar'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=200, verbose_name='가게이름')),
                ('location', models.CharField(max_length=100, verbose_name='지역')),
                ('semi_location', models.CharField(max_length=100, verbose_name='세미지역')),
                ('images', models.ImageField(upload_to='stores_images/', verbose_name='대표 이미지')),
                ('greetings', models.TextField(max_length=200, verbose_name='인삿말')),
                ('category', models.CharField(max_length=10, verbose_name='분야')),
                ('connexion', models.IntegerField(verbose_name='단골')),
                ('days', models.CharField(max_length=100, verbose_name='요일')),
                ('open_time', models.CharField(max_length=100, verbose_name='여는 시간')),
                ('close_time', models.CharField(max_length=100, verbose_name='닫는 시간')),
                ('menu_items', models.ImageField(upload_to='stores_images/', verbose_name='메뉴 이미지')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
