# Generated by Django 4.2.5 on 2023-10-02 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_menuitem_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='connexion',
        ),
    ]
