# Generated by Django 4.2.5 on 2023-09-28 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_user_chatroom_seller_chatroom_buyer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='seller',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='buyer',
        ),
    ]
