# Generated by Django 4.2.5 on 2023-10-03 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_store_connexion'),
        ('app', '0008_rename_seller_chatroom_user_remove_chatroom_buyer'),
    ]

    operations = [
    ]
